### ISSUE TITLE
ASTKernel.plan_cpu unstable w.r.t. Py version

### ISSUE THREAD

**Issue by blechta** [coneoproject/COFFEE#106]
The result of `ASTKernel.plan_cpu` is different with different Python versions. See http://fenics-bamboo.simula.no:8085/browse/FFC-FDT0-17/artifact/RTPY3/error.log/error.log.

**Comment by miklos1** [comment]
Does it help if you use the branch from #105?

**Comment by blechta** [comment]
Partially, the diff shrank from 157Kbytes to 100Kbytes.

**Comment by wence-** [comment]
Note that we can't see that file (or at least I can't, it's behind a login).

**Comment by FabioLuporini** [comment]
I confirm I can't see the file.

**Comment by blechta** [comment]
[error-before-105.log.txt](https://github.com/coneoproject/COFFEE/files/627241/error-before-105.log.txt)
[error-after-105.log.txt](https://github.com/coneoproject/COFFEE/files/627240/error-after-105.log.txt)

**Comment by FabioLuporini** [comment]
I'll take a look later.

Meanwhile, two things:
- seems like you're somewhat bypassing the ``postprocess`` function, which is applied in ``plan.py`` right before translating the kernel into a string
- out of curiosity: could you show me how you initialise coffee? 

Thanks

**Comment by blechta** [comment]
Hold on. I think I have produced those without `glpsol` installed which was hidden to me due to https://bitbucket.org/fenics-project/ffc/issues/136. I'll open a new issue.
