### ISSUE TITLE
COFFEE optimisations shouldn't change kernel signature

### ISSUE THREAD

**Issue by wence-** [coneoproject/COFFEE#14]
Consider a bilinear form assembly that produces a local 2x1 tensor.  With O2 on, this gets padded to `A[2][2]` (from `A[2][1]`).  The current state of affairs is that the responsibility for feeding the correctly sized (padded) buffer to the kernel and unpicking it afterwards is that of the caller of the kernel.  But this means that for every new padding (or other layout-changing strategy) that coffee employs, the wrapper code generator must also be updated.  Leading to two sources of potential bug, and two places that must be kept in sync.  I suggest that it would be better for this transformation to belong entirely to coffee and live inside the kernel (thus keeping the signature unchanged).

```c

void foo(double A[2][1], ...)
{
     double A_pad[2][2];

     ...
      A_pad[i][j] += ...;
    
     unpack(A, A_pad);
}```

**Comment by FabioLuporini** [comment]
Done, so closing.
