### ISSUE TITLE
Per Backend Planning

### ISSUE THREAD

**Issue by chromy** [coneoproject/COFFEE#22]
We want COFFEE to be able to generate backend specific code (for example generating code with CUDA specific keywords). I talked about this with Fabio and we think the best way is to introduce backend specific coffee.plan.ASTKernel subclasses.

**Comment by chromy** [comment]
This will require changes to PyOP2, I'm not sure what the strategy is for landing breaking changes, but if we don't want to see any broken state between the changes we could land the patches like this:
Add the subclasses: #23 
Change PyOP2 to use them OP2/PyOP2#422
Move the implementation: #24

**Comment by FabioLuporini** [comment]
CUDA support in PyOP2 has been dropped, so I'm also closing this. Someone else will think about GPUs in the future.
