### ISSUE TITLE
Form does wrong thing with tensors

### ISSUE THREAD

**Issue by colinjcotter** [coneoproject/COFFEE#45]
The following code:
https://gist.github.com/wence-/f26a73724e46181a345e

generates equivalent forms two different ways. With parameters["coffee"]["O2"] = False
they produce the same answer, otherwise they don't.

**Comment by FabioLuporini** [comment]
This *really* was a subtle one! Thanks Colin for pointing it out.

I have a fix (which I want to test more deeply) which will land together with a branch I'm about to merge. Will keep you posted.

Thanks

**Comment by FabioLuporini** [comment]
Fixed
