### ISSUE TITLE
LICM breaks for some 2-forms

### ISSUE THREAD

**Issue by wence-** [coneoproject/COFFEE#49]
Bringing over the example from firedrakeproject/firedrake#511, if a sum of mass matrices is assembled on a vector-valued space, we get the wrong answer.  firedrakeproject/firedrake#513 introduces a number of tests to exercise this, but a minimal example is:

```python
from firedrake import *
from numpy import array
parameters["coffee"]["O2"] = True
parameters["assembly_cache"]["enabled"] = False
mesh = UnitTriangleMesh()
V = VectorFunctionSpace(mesh, "CG", 1)

u = TrialFunction(V)
v = TestFunction(V)

c = Constant(2)
a = (c*inner(v,u))*dx + inner(v,u)*dx
A = assemble(a)
print A.M.values - 3*assemble(inner(v, u)*dx)
[[-0.08333333  0.         -0.04166667  0.         -0.04166667  0.        ]
 [ 0.         -0.08333333  0.         -0.04166667  0.         -0.04166667]
 [-0.04166667  0.         -0.08333333  0.         -0.04166667  0.        ]
 [ 0.         -0.04166667  0.         -0.08333333  0.         -0.04166667]
 [-0.04166667  0.         -0.04166667  0.         -0.08333333  0.        ]
 [ 0.         -0.04166667  0.         -0.04166667  0.         -0.08333333]]
```

I expect to see zeros.

**Comment by FabioLuporini** [comment]
Assuming you meant to write "... 3*assemble(inner(v, u)*dx).M.values", on my branch enhance_rewriter I get:
array([[  5.55111512e-17,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   5.55111512e-17,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   5.55111512e-17,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   5.55111512e-17]])

which looks like what we want. So I'll bring this branch to a mergeable state on Monday (it already passes all tests)

**Comment by wence-** [comment]
Yes, that's right.  There are now some xfailed tests in firedrake master to check against.

**Comment by FabioLuporini** [comment]
Fixed.
