### ISSUE TITLE
Unknown Error Log

### ISSUE THREAD

**Issue by alsgregory** [coneoproject/COFFEE#63]
Hi, 

I have a persistent error with multiple Firedrake codes which I think has been stemming from COFFEE. The Firedrake py script is attached, test_QG_Firedrake.txt, the err file (err.txt) and the c code in which it references c.txt is also attached. Sorry they are in txt form, it's all Github takes on this attachment.

Could you possibly help me understand what they mean?

Many Thanks,
Alastair Gregory

[test_QG_Firedrake.txt](https://github.com/coneoproject/COFFEE/files/90448/test_QG_Firedrake.txt)

[c.txt](https://github.com/coneoproject/COFFEE/files/90451/c.txt)
[err.txt](https://github.com/coneoproject/COFFEE/files/90452/err.txt)

**Comment by FabioLuporini** [comment]
Hi,

thanks very much for reporting this. I should have a fix in a branch called fix-min-temporaries. We are trying to merge this branch ASAP, but if you don't want to wait, you can just checkout this branch and give it a go. Keep you posted

**Comment by FabioLuporini** [comment]
This was fixed some I'm closing it
