### ISSUE TITLE
Selecting optimisations a bit odd

### ISSUE THREAD

**Issue by wence-** [coneoproject/COFFEE#8]
Imagine I do:

```
parameters['O2'] = True
parameters['O0'] = True
```

And pass these as options to `plan_cpu`, O2 optimisation will be selected.  I wonder if a better way is to have a single "optimisation_level" parameter that defaults to 2.

**Comment by FabioLuporini** [comment]
This is fixed as now one chooses the optimisation level setting 

`parameters['optlevel'] = O0 (O1, O2..)`

I'm closing this

**Comment by miklos1** [comment]
> This is fixed as now one chooses the optimisation level setting
> ```python
parameters['optlevel'] = O0 (O1, O2..)
```

Is this documented anywhere?

**Comment by FabioLuporini** [comment]
coffee.system

**Comment by wence-** [comment]
I think he means, in user-facing docs.  We should have a "misc" section in the firedrake docs about this stuff.

**Comment by FabioLuporini** [comment]
Ah, yes. I'll write something (mostly what's in coffee.system + epsilon)
