### ISSUE TITLE
Compilation error with COFFEE optimizations

### ISSUE THREAD

**Issue by stephankramer** [coneoproject/COFFEE#81]
How to reproduce:

Build firedrake with --adjoint, checkout the 'adjoint' branch of git@github.com:thetisproject/thetis.git and remove line 97 of test_adjoint/test_swe_adjoint.py to re-enable COFFEE optimizations. Then run with:

py.test -ksetup1 -svv test_adjoint/

This produces, during the running of the adjoint model, some form for which the code does not compile. See zip file for code and compilation error:

[68da85872519e65158924d2312a25638_p10342.zip](https://github.com/coneoproject/COFFEE/files/339338/68da85872519e65158924d2312a25638_p10342.zip)

**Comment by FabioLuporini** [comment]
Thanks Stephan, i'll look into it very soon. 

Is there a reason coffee was disabled in the first place? Or is this simply a long standing issue ?

I assume you're running with updated coffee ?

Thanks

**Comment by stephankramer** [comment]
The adjoint capability of thetis was only added recently (and the necessary functionality for this in firedrake-adjoint/dolfin-adjoint). This was in a sprint right after Fenics '16, and because at that point we were expecting and hitting various other bugs, we decided to temporarily switch off coffee to simplify debugging (i.e. to separate out firedrake-adjoint bugs from possible coffee bugs).

This is with up-to-date COFFEE indeed.

**Comment by FabioLuporini** [comment]
OK, that makes sense. I'm on it, keep you posted

**Comment by FabioLuporini** [comment]
PR #82 should fix this. I've run the thetis tests and they all pass; i'm running the firedrake tests and they all seem to pass. Feel free to try it, but it's gonna be merged soon
